In [108]:
import numpy
# مهم نیست و خطایی نمیدهد اگر در ادامه دوباره ایمپورت کنیم اما بهتر است یبار بیشتر انجام ندهیم

In [109]:
yek = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]
print(type(yek))

<class 'list'>


In [110]:
nyek = numpy.array(yek)
nyek

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
numpy.diag(nyek)

array([1, 5, 9])

In [112]:
matrix = numpy.zeros((2, 2))
matrix

array([[0., 0.],
       [0., 0.]])

In [113]:
numpy.diag(matrix)

array([0., 0.])

In [114]:
matrix = numpy.ones((4, 4))

In [115]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [116]:
numpy.diag(matrix)

array([1., 1., 1., 1.])

In [117]:
m1 = numpy.zeros((3, 4), int)
m1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [118]:
m2 = numpy.ones((3, 4), int)
m2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [119]:
numpy.vstack([m1, m2])
# V : VERTICAL عمودی
# برای این دستور باید تعداد مولفه های دوم(ستون ها) در هر لیست برابر باشد

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [120]:
numpy.hstack([m1, m2])
# H : HORIZONTLE افقی
# برای این دستور باید تعداد مولفه های اول(سطر ها) در هر لیست برابر باشد

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])

In [121]:
# برای اجرای دو دستور بالا، ترتیب ورودی ها در ترتیب خروجی موثر است

In [122]:
[1, 2, 3] * [4, 5, 6]
# ضرب لیست ها بدون تبدیل آنها به نامپای امکان پذیر نیست

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])
z = x * y
z

In [123]:
x ** 2

array([1, 4, 9])

In [124]:
x.dot(y)
# dot : ضرب داتی یعنی ضرب نظیر به نظیر عناصر هر لیست با ترتیب اولی در اولی، دومی در دومی، ... و در آحر جمع همه ی انها باهم

np.int64(32)

In [125]:
nyek

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
nyek.T
# T = TRANSE جای سطر ها را با ستون ها عوض میکند
# We should write T NOT t
# ndo = nyek.T این دستور یک متغیر دیگر تعرف نمیکند و به متغیر دیگر دست نمیزند گویی این دستور را وارد کرده ایم

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [127]:
nyek.astype('f')
# تایپ را از حالت اینتیجر(عدد صحیح) به فلوت(عدداعشاری) در یک متغیر دیگر تغییر میدهد

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [128]:
nyek.sum()
# جمع مقادیر عناصر جداول

np.int64(45)

In [129]:
nyek.max()
# بزرگترین مقدار جداول را نشان میدهد

np.int64(9)

In [130]:
nyek.min()
# کوچکترین مقدار جداول را نشان میدهد

np.int64(1)

In [131]:
nyek.argmax()
# جایگاه(ایندکس) بزرگترین عدد را نشان میدهد که چندمین عنصر ماتریس است(فرایند شمارش از صفر شروع میشود)

np.int64(8)

In [132]:
nyek.argmin()
# جایگاه(ایندکس) کوچکترین عدد را نشان میدهد که چندمین عنصر ماتریس است(فرایند شمارش از صفر شروع میشود)

np.int64(0)

In [133]:
nyek.mean()
# میانگین عناصر

np.float64(5.0)

In [134]:
nyek.std()
# انحراف استاندارد عناصر

np.float64(2.581988897471611)

In [142]:
mr = numpy.arange(15) ** 2
# یعنی از رنج صفر تا چهارده(پانزده عدد) یک آرایه ی نامپایی بساز و در آخر به توان دو کن
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [143]:
mr[2]
# یعنی ایندکس دو را به من نشان بده

np.int64(4)

In [144]:
mr[2 : 6]
# یعنی ایندکس دو تا شش را به من نشان بده

array([ 4,  9, 16, 25])

In [149]:
mr[ : 6]
# یعنی ایندکس هیچی(اول) تا شش را به من نشان بده

array([ 0,  1,  4,  9, 16, 25])

In [150]:
mr[6 : ]
# یعنی ایندکس شش تا هیچی(آخر) را به من نشان بده

array([ 36,  49,  64,  81, 100, 121, 144, 169, 196])

In [151]:
mr[-5 : ]
# یعنی ایندکس از آخر پنجی تا آخر را به من نشان بده

array([100, 121, 144, 169, 196])

In [152]:
mr[ : -2]
# یعنی از هیچی(اول) تا از آخر دومی را به من نشان بده

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [160]:
mr[4 : 13 : 2]
# از ایندکس چهار تا سیزده، دوتا دوتا برو جلو و انتخاب کن و به من نشان بده

array([ 16,  36,  64, 100, 144])

In [159]:
mr[4 : : 2] 
#  or mr[4::2]
# یعنی از ایندکس چهار تا هیچی(آخر) دوتا دوتا برو جلو و انتخاب کن و به من نشان بده

array([ 16,  36,  64, 100, 144, 196])

In [161]:
mr[4 : : -2]
# یعنی از ایندکس چهار تا هیچی(چون قدم برداری معکوسه، پایان این دستور همان اول است) دوتا دوتا برو عقب و انتخاب کن و به من نشان بده

array([16,  4,  0])

In [162]:
mr[-10 : -2 : 2]
# یعنی از ایندکس از آخر دهمی تا از آز آخر دومی دوتا دوتا برو جلو و به من نشان بده

array([ 25,  49,  81, 121])